name: Main-workflow
env: # Set the secret as an input
  docker_username: anya-ayob
  docker_password: ${{ secrets.GITHUB_TOKEN }} #Nees to be set to be made available to the workflow
  GIT_commit: ${{ github.sha }}

on:
  push:
    branches: main
  pull_request:
    branches: main
  workflow_dispatch: 

jobs:
  Build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Clone down repository
        uses: actions/checkout@v5    
        
      - name: Build the application
        run: ci/build-app.sh
        
      - name: Test
        run: ci/unit-test-app.sh
        
      - name: Upload repo
        uses: actions/upload-artifact@v4
        with: 
          name: code
          path: .
          include-hidden-files: true
          
  Linting:
    runs-on: ubuntu-latest
    needs: [Build]
    steps:
      - name: Download code
        uses: actions/download-artifact@v4
        with: 
          name: code
          path: .
          
      - name: run linting
        uses: super-linter/super-linter/slim@v7
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISABLE_ERRORS: true 
          
  Dockerimage:
    runs-on: ubuntu-latest
    needs: [Build]
    permissions:
      packages: write
    steps:
      - name: Download code for container
        uses: actions/download-artifact@v4
        with:
          name: code
          path: .

      - name: Build docker
        run: bash ci/build-docker.sh
        
      - name: Push docker
        run: bash ci/push-docker.sh


